import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Go Drive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <div className="p-1 bg-gradient-to-r from-pink-700 to-purple-700"></div>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
